### ISSUE TITLE
It's simply not working

### ISSUE THREAD

**Issue by ishanSrt** [nemisj/git-removed-branches#3] opened 2017-12-14 14:31 UTC
After one of my branches got merged and I deleted that on GitHub, I installed this though npm, and while on the same branch I ran the command to delete the branch. It asked me to run `git fetch -p` I ran it, but still its issuing me the command to run `git fetch -p` again.

**Comment by nemisj** [comment] 2018-01-09 16:29
@ishanSrt, Sorry, I can't reproduce your issue, do you have more information for me?

**Comment by ishanSrt** [comment] 2018-01-09 16:31
@nemisj can't test it out right now. you should consider improving the documentation as it did not work correctly the first time and now I have now git used to deleting branches manually 😛

**Comment by nemisj** [comment] 2018-01-09 18:57
Sorry, but you're the first one since Sep 28, 2015 who experiencing such behavior, I'm using this tool every day and a lot of colleges of mine too, but non of them had issue you've described. I'm willing to improve code, but I don't know what the problem exactly is. I'm closing this ticket for now, till you can provide detailed reproduction.

**Closed by nemisj** 2018-01-09 18:57 UTC
